# Pandas: Analyzing
___
- EG: `df.describe()`, `len(df)`
- Now that we have Inspected and Cleaned the Data, it's finally time to Analyze it
- We will focus on 2 main features of Pandas for analyzing Data that you should know:
    - Aggregating our Data (Min, Max, Count, ETC...) - `df.describe()`
    - And also in a larger picture, actually Grouping the Data so going into things like Analyzing Job Countries or Job Titles, etc...

In [17]:
import pandas as pd
from datasets import load_dataset

# Load the Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [18]:
# Only way to include DateTime information as just Running the .describe() won't bring it up since that way is Depreciated
df.describe(datetime_is_numeric=True)

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785727 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

- Anytime we are starting to do any Analysis, the 2 Methods that should be used first are:
    - `df.describe()`
    - `df.info()`

- There are a lot of different Methods that can be used to Analyze Data on the Data Frame and even the Columns themselves
    - This is to better understand the Key Statistics about a Column
    - **Note: We aren't going to do all of these, we are only going to do a few**
        - `df.count()` - Count of Values
        - `df.sum()` - Sum of Values
        - `df.cumsum()` - Cumulative Sum of Values
        - `df.min()/df.max()` - Minimum/Maximum Values
        - `df.idxmin()/df.idxmax()` - Indexes of MIN/MAX Values
        - `df.mean()` - Mean of Values
        - `df.median()` - Median of Values
        - `df.mode()` - Mode of the Values
        - `df.column_name.value_counts()` - Unique Counts

In [ ]:
# As a point, the info() Method already shows a Count of all of those Columns but we can also Run:
df.count()
# Which gives us the same Number of Results

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785727
job_skills               668704
job_type_skills          668704
dtype: int64

In [ ]:
# Moving to more of a Numerical Analysis, we want to get the Median Value, we Run:
df.median()
# This Value is not included in the describe() Method

C:\Users\Neill\AppData\Local\Temp\ipykernel_4368\1217397539.py:2: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df.median()
C:\Users\Neill\AppData\Local\Temp\ipykernel_4368\1217397539.py:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.median()

job_work_from_home            0.00
job_no_degree_mention         0.00
job_health_insurance          0.00
salary_year_avg          115000.00
salary_hour_avg              45.98
dtype: float64

- Regarding the `describe()` Method, when we Ran it before, it provided a lot of the Key Statistics in there
    - But specifically with the Min and Max, sometimes when this is provided, we would want to go in further and investigate what's going on here because we may have very strange Values
    - In this case, we have a Minimum Salary of $15,000 which is extreamly low... so, let's investigate!

In [ ]:
# First to Confirm that Value, we are going to Run the Min Method on this
df['salary_year_avg'].min()

15000.0

In [24]:
# Now to Run the other Method of idxmin(). This gets the Index Value of where this Minimum Salary Lives
# It's essentially a CTRL + F
min_salary = df['salary_year_avg'].idxmin()

In [ ]:
# Now to access this and get back the Record, use the iloc Property on this Data Frame and specify the Index of the Minimum Salary (which is inside our Variable)
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

- Investigating this further with ChatGPT to see if this is good money in Brazil:
    - Our findings indicate:
        - No, a $15,000 USD monthly salary is not "normal" in Brazil—it is extremely high and places an individual well within the top 1% or even top 0.1% of earners. 
        - With that income, you would be living a luxurious, upper-class lifestyle, likely far exceeding the salary of senior executives or specialized professionals in Brazil.
- Because of these findings, this isn't an anomoly!

In [26]:
# To get back an Array of all the unique job titles, simply use:
df['job_title_short'].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

- While this is cool and all, it doesn't really provide much Value...
- We want to find out, what are the Unique Value Counts associated with these Jobs!
    - And for this, the `.value_counts()` Method will do the trick!

In [27]:
df['job_title_short'].value_counts()

Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: job_title_short, dtype: int64

- Not only does it provide, Numerical Counts but it also Organizes it in DESC Order!
    - So we can see that **Data Analyst**, **Data Engineer**, and **Data Scientist** take up the majority of all the Roles and are the 3 most highest
    - Then we have **Business Analyst**, and **Software Engineer**, followed by the Senior Roles of **Senior Data Engineer**, **Senior Data Scientist**, and **Senior Data Analyst**
    - Then finally, we close this out with **Machine Learning Engineer** and **Cloud Engineer**

- We have beein using these Statistical Methods, but we've only really used it on one off Calculations...
- What happens, if we want to dive deeper now into understanding multiple different aspects...
    - Like, what is the miniumum salary of all of the different job_title_shorts?
- Well, as you guess it! There is a Method for this!
    - And it's `pandas.DataFrame.groupby`. The Syntax is as follows:
    - `df.groupby('columns to group')['columns to aggregate'].your_agg_method()`
- After we have Grouped our Data, we can perform a lot of the different Methods, that we mentioned at the start of this Lesson such as Min, Max, Count...

In [ ]:
# Question: What is the Miniumum Salary of all of the different job_title_shorts?
df.groupby('job_title_short')['salary_year_avg'].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

- We not only see that lowest Role that we found earlier: The **Data Engineer** at $15,000, but also a whole host of other ones in there!
- Now that we have that, let's answer another Question that is a better representation of the Data itself.

In [29]:
# Question: What is the Median Salary of all of the different job_title_shorts?
df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

- Let's manipulate this even further...
- We learned that there are Fluctuations in Salaries to different Countries so we can also do a Group By, not only by the **job_title_short** but also by the **Country**
    - To do this, the Syntax is as follows:
    - `df.groupby(['list of columns to group'])[['list of columns to aggregate']].your_agg_method()`

In [33]:
# Question: What is the Median Salary of all of the different job_title_shorts in all the different job_country?
df.groupby(['job_title_short', 'job_country'])['salary_year_avg'].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

- Now that we have this, we learned how to do multiple Group By's of the different Columns that we want to do
    - What if we want to perform Aggregations on multiple columns?
    - Because we have access to **salary_year_avg** and the **salary_hour_avg**, what happens if we want to look at both?

In [35]:
# Question: What is the Yearly Median Salary and Hourly Median Salary of all of the different job_title_shorts?
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].median()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

- Last thing to cover with the Group By:
    - Yeah we can get the Minimum Values of the Job Titles for the Yearly Salary, but what happens if we also want the Max Values in there too??
    - So we want to do multiple different operations or Aggregation Methods on the Data...
        - Well, ofc! There's a Method for that!
        - It's called `.agg()` and inside of there we need to provide a List of Arguments
    - To do this, the Syntax is as follows:
    - `df.groupby(['list of columns to group']).agg(['list of aggregation methods'])`

In [36]:
# Question: What is the Yearly Min, Max, Median Salary of all of the different job_title_shorts?
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max', 'median'])

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0