# Advanced - Pandas: Data Management
___
- EG: `df.sample(), df.copy()`
- In this Section, we are going to be Focussing on 2 important Functions that are used all the time for Data Management
    1. We will go over the `df.sample()` Method which is pretty straight forward
    2. Then covering the `df.copy()` Method which looks easy on the surface, is a lot more Advanced

In [3]:
# Imports
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

- From before we had 2 Methods to look at the Data
    - `df.head()` - Looks at the First 5 Records
    - `df.tail()` - Looks at the Last 5 Records
- Problem is, what is Returned, is not necessarily representitstic of the Dataset itself
- These Methods could Return the same information, such as the last 5 Records could be Job Postings in Germany, which would lead an assumption that this Dataset is all German Job Postings
    - This is not true ofc, but one that hasn't thoroughly looked at the Data could get led to that conclusion
    - Because of this there's not necessarily a true Sample... of the Data

In [4]:
df.tail()

          job_title_short  ...                                    job_type_skills
785736  Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737       Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738   Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739      Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740  Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[5 rows x 17 columns]

- Luckily, in cases like this we do in fact, have a Method for that!
- Similar to the `head()` and `tail()` Methods, we have the `sample()` Method
    - `pandas.DataFrame.sample`
        - This Returns a Random Sample of Items from an Axis of Object
        - Just like `head()` and `tail()`, we can specify the number to Sample
        - Or specify the fraction of Float. How much of the Fraction of Data to Return
- Running this Method on our Data Frame we get back a Sampling Result
    - We can tell this by the Index on the left, as it's sporadic and varied on what Jobs are Returned as they are not in sequential Order
    - So this is super useful to use
        - Something to Note, everytime this is Ran, it will provide new/different Results within this Sample
    - If you have a certain Example, that you find through your `sample()` you can actually Output the same Results every single time by setting the `random_state` Argument inside `sample()`
        - This is seen further down (Keep Scrolling)
        - Now when Running this, the same Results are going to Return every. single. time.
        - Now, we don't have to worry about any Variation in what we are Returning back

In [7]:
# Sample Method
df.sample(10)

            job_title_short  ...                                    job_type_skills
187037     Business Analyst  ...                                                NaN
166614        Data Engineer  ...  {'analyst_tools': ['power bi'], 'cloud': ['aws...
119698         Data Analyst  ...  {'analyst_tools': ['sas'], 'programming': ['py...
769707         Data Analyst  ...  {'analyst_tools': ['excel', 'power bi', 'sap']...
241759        Data Engineer  ...                                {'os': ['windows']}
143688       Data Scientist  ...  {'analyst_tools': ['excel'], 'libraries': ['te...
194482  Senior Data Analyst  ...  {'analyst_tools': ['powerpoint', 'word', 'exce...
359251        Data Engineer  ...  {'cloud': ['databricks', 'aws'], 'libraries': ...
2109         Data Scientist  ...  {'databases': ['elasticsearch'], 'libraries': ...
241992        Data Engineer  ...  {'cloud': ['aws', 'redshift', 'snowflake', 'or...

[10 rows x 17 columns]

In [30]:
# Sample Method using the random_state Argument
df.sample(10, random_state=42)

              job_title_short  ...                                    job_type_skills
502901   Senior Data Engineer  ...  {'cloud': ['azure'], 'other': ['git'], 'progra...
406337  Senior Data Scientist  ...  {'analyst_tools': ['looker'], 'cloud': ['bigqu...
659951          Data Engineer  ...                                                NaN
541593           Data Analyst  ...                                {'async': ['jira']}
425158   Senior Data Engineer  ...                        {'programming': ['python']}
183426           Data Analyst  ...  {'analyst_tools': ['tableau'], 'cloud': ['orac...
287790           Data Analyst  ...  {'analyst_tools': ['excel'], 'libraries': ['ha...
541983           Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau', 'qli...
416896         Data Scientist  ...                                                NaN
780907          Data Engineer  ...  {'analyst_tools': ['alteryx'], 'cloud': ['orac...

[10 rows x 17 columns]

- Next Method we are going to cover is `copy()`
    - `pandas.DataFrame.Copy`
        - Make a Copy of this Object's Indices and Data
- Let's do some Practice with this Method
    - Let's Create a New Data Frame called `df_original` and all we are doing is Loading our Dataset into it

In [31]:
# Creating a New Data Frame and Loading our initial Data Frame into it
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [32]:
# Inspecting our Data Frame to Confirm everything is in there and it's the same as the Original
df_original

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                                NaN
1               Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2              Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4              Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                      ...  ...                                                ...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]

- As expected from the name of the Method, the `df.copy()` Method Creates a Copy of the Data Frame
- Now, you may be wondering, why do we need to use this `df.copy()` Method?
    - Because usually all we need to do is this: `df_altered = df_original` (where we Create this new Data Frame, `df_altered` and it's equal to the Original Data Frame, `df_original`)
    - And then if we were to Print out the `df_altered`, everything would be in there and we'd get a perfect Copy back
- So what's the purpose of this whole `df.copy()` Method?
- Well... let's look at this, using an Example
- But as a short Explanation:
    - When we do the Assigning, the Unique ID assigned to the Data Frame, is also given to the New Data Frame
    - So any changes we do to the Altered, will be done to the Original, since they will have the same ID's
    - This is bad, because when we do multiple different Calculations to Multiple different Data Frames, we don't want them Altered, because what's the point in having different Data Frames?
    - Now all the Data gets compromised and it becomes a mess
    - That's why when we Create a Copy of the Data Frame, it will Create a True Data Copy, but will Assign it a New ID and leave the Original intact
    Quick EG:
    1. `df_altered = df_original`
    2. `df_altered` has ID 12345 
    3. `df_original` also now has ID 12345
    4. We do an override of NaN Values for `df_altered`. Where we Replace the NaN Values with the Median Values
    5. Expected Outcome: `df_altered` has the NaN Values Replaced with Median Values and `df_original` remains intact and is untouched by the Operation
    6. Actual Outcome: Not only has `df_altered` NaN Values been Replaced with Median Values but `df_original`'s NaN Values have also been Replaced by Median Values
    7. This is because they share the same ID or Unique Identifier - different to Memory Location
    8. To Prevent this, we use the `df.copy()` Method so the Data is a Perfect Copy, but the Unique ID for the Data Frame is different, thus any alterations are only made to the New Data Frame, leaving the Original untouched and intact

In [33]:
# Assigning our Original Data Frame into a New Altered Data Frame Variable
df_altered = df_original

In [ ]:
# Looking at the Previous Example where we Replaced the NaN Values with the Median salary_year_avg Value
# Inspecting this Altered Column, we can see most of them have NaN Values (All of the shown 5 have NaN Values)
df_altered.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [39]:
# Calculate the Median Salary
median_salary = df_altered['salary_year_avg'].median()
# Printing it out
median_salary

np.float64(115000.0)

In [41]:
# Using the Altered Data Frame, Fill in those NaN Values with the Median Salary Value we Calculated
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

# Print out those Values to show our work
df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

- Now we can see those NaN Values previously are now Filled in with that Median Value of 115,000
- But... what about our Original Data Frame? -> `df_original`
- Those should still be Nan Values.... right? Since we didn't touch those!
    - Well actually... as you can see below, they are not... and they are now Updated
- When Inspecting it, we actually find, that the Original Data Frame actually got Updated just as our Altered Data Frame did

In [42]:
# Inspecting the Original Data Frame
df_original.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

- This is not a good thing! Because:
    - Technically, we can have multiple different Data Frames that have done multiple different Calculations on and we wouldn't want those Calculations on 1 Data Frame to affect the other
    - So... why is this happening?
- Well, it has to do with the fact of how we Assigned `df_altered = df_original`
    - When we used this Assignment Operator (`=`), the `df_original` had a Data Frame in it that had a Unique ID
    - This new `df_altered` was also set equal to that same Data Frame
- That is all a bunch of Theory, so let's go and prove it!

In [ ]:
# Getting the Unique ID of the Original Data Frame
id(df_original)

1412588212880

In [44]:
# Getting the Unique ID of the Altered Data Frame
id(df_altered)

1412588212880

- Comparing the 2 Results. The Numbers are the same!
- Looking at the Returned Values we can see that these Numbers are identical and this proves they are sharing the same Unique ID

In [45]:
# Because we are too lazy to Compare Number by Number to Prove they are the same
# We can just use the Comparison Operator to do this for us
id(df_original) == id(df_altered)

True

- So, these Variables are Referencing the same Data Frame... which is very not good!
- Now, let's show this in action
    - Let's Reload the Data Set so we have this Unique ID for our `df_original`

In [46]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

- Now let's Create that `df_altered` again and we will set it equal to `df_original`
- But this time, let's use the `df.copy()` Method alongside it

In [47]:
# Creating df_altered and setting it equal to df_original but invoking our Copy Method
df_altered = df_original.copy()

In [48]:
# Fancy Print Statements like before where we show the ID's of: Original, Altered and Comparing the two
print('ID of df_original:                ', id(df_original))
print('ID of df_altered:                 ', id(df_altered))
print('Are the two Data Frames the same? ', id(df_original) == id(df_altered))

ID of df_original:                 1412587791376
ID of df_altered:                  1412588318160
Are the two Data Frames the same?  False

- With this, we can see that the `df_altered` Data Frame is different
- And it also Confirms this with the Comparison Operator saying that it is False
- And now we Calculate that Median Salary that will Replace the NaN Values in the `salary_year_avg` Column

In [50]:
# Calculating the Median Salary
median_salary = df_altered['salary_year_avg'].median()

- Replace the Nan Values with the Calculated Median Salary Value

In [51]:
# Replacing NaN Values with the Median Salary Value
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

# Printing out those Values to show our work
df_altered.loc[:5, 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

- It's done correctly on `df_altered` as we can see

In [52]:
# Printing out those Values to Prove that the Original is untouched
df_original.loc[:5, 'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

- For `df_original`, this one is **unaltered**

### Closing Remarks:
___
- From here on out, we are going to be using this new `df.copy()` Method anytime we need to Create a Copy of the Data Frame and do some sort of Operations on it
- This is basically to Protect us to make sure that we are not causing harm somewhere else