# Pandas - Exporting DataFrames
___
- EG: `df.to_excel(), df.to_csv()`
- With the last Example, we were able to Extract out those Quarter 1 Results, into it's own individual DataFrame
- The next step, whci I'm sure the boss actually wants is an Excel File of all of this Data
    - What we are going to do in this Section and explore all the popular Methods that are used to Export Data to a File that even others can use

- In this Example, we are going to be picking up, right where we left off from last lesson with the `df_q1` Results
- Where we Created that DataFrame on Quarter 1 Results using the Dictionary with January, February and March in there
- And this DataFrame has over 220k Rows, so we are going to be Exporting a lot of Rows to a File
    - Now to bring that Data into this Lesson
    - All I'm going to do is Re-Create everything we did last Lesson

In [1]:
# Imports
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading the Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
# Create a New Column that will Contain only the Shorthand Month Value
df['job_posted_month'] = df['job_posted_date'].dt.strftime('%b')

In [6]:
# Creating an Array of all the Different Months
months = df['job_posted_month'].unique()

In [9]:
# Creating a Dictionary Comprehension
dict_months = {month: df[df['job_posted_month'] == month] for month in months}

In [11]:
# Running the concat Function to combine all this Data
df_q1 = pd.concat([dict_months['Jan'], dict_months['Feb'], dict_months['Mar']], ignore_index=True)

In [12]:
# Printing out our DataFrame
df_q1

          job_title_short  ... job_posted_month
0            Data Analyst  ...              Jan
1          Data Scientist  ...              Jan
2           Data Engineer  ...              Jan
3           Data Engineer  ...              Jan
4          Data Scientist  ...              Jan
...                   ...  ...              ...
220479  Software Engineer  ...              Mar
220480       Data Analyst  ...              Mar
220481   Business Analyst  ...              Mar
220482      Data Engineer  ...              Mar
220483  Software Engineer  ...              Mar

[220484 rows x 18 columns]

- Let's Explore what Methods are actually Available to Export our Data
- We are going to do this by typing in `.to_`
    - This provides a whole host of options that we can use
    - The main ones we are going to be looking at are `.to_clipboard`, `.to_csv`, `.to_excel` and we will talk about things like `.to_sql`, `.to_pickle` and also `.to_parquet` File

In [13]:
# Starting off with the .to_clipboard Method
df_q1.head().to_clipboard(sep=",")

- We don't want to Copy everything to Clipboard or else it will Crash, so we are only specifying 5 Values by using `.head()`
    - For the `.to_clipboard`, we need to specify `sep=","`
    - That way it knows, that whenever we Copy this, put Commas in between each of these Values
- After it Runs, we know it has been Copied Successfully and to Test this we can Paste the Contents into a Markdown Cell using CTRL + V

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
0,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,,,,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau'], 'programming': ['r', 'python', 'sql', 'nosql']}",Jan
1,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,,,,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'scikit-learn', 'matplotlib', 'hadoop', 'spark']","{'libraries': ['pandas', 'numpy', 'scikit-learn', 'matplotlib', 'hadoop', 'spark'], 'programming': ['r', 'python', 'sql']}",Jan
2,Data Engineer,Data Engineer,"Fort Worth, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-25 13:24:01,False,False,United States,,,,Programmers.io,"['sql', 'python']","{'programming': ['sql', 'python']}",Jan
3,Data Engineer,Data Engineer,"San Mateo, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-28 13:07:30,False,True,United States,,,,Verkada,"['sql', 'python', 'aws', 'looker']","{'analyst_tools': ['looker'], 'cloud': ['aws'], 'programming': ['sql', 'python']}",Jan
4,Data Scientist,Data Scientist,"São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-03 23:02:27,False,False,Brazil,,,,Mars,"['python', 'sql', 'azure']","{'cloud': ['azure'], 'programming': ['python', 'sql']}",Jan

- As we can see, we get the first 5 Rows of Data into our Clipboard!
- Moving into the next one, `.to_csv`
    - Used when we are frequently doing some sort of Analysis and Creating different DataFrames. We want to Export in and Save that DataFrame in case we want to Access it and Analyze it in the future
- Inside of `.to_csv`, we are going to specify the File Name that we want it to Save to
- After Running, we can see that the File has been Saved and it's in the same Folder as where I am Saving all these Files

In [14]:
# Moving onto the .to_csv Method
df_q1.to_csv('quarter_1')

- Inspecting it, we can see, it is Saved as a CSV, but it doesn't have the correct File Extension appended to it
- Whenever you Run this, you need to Run it with the File Extention that you want to Save it as 
    - In this case, we want to Save it to a .CSV

In [15]:
# Running it with the Extension Added
df_q1.to_csv('quarter_1.csv')

- We can see that it was Saved into the Folder with the correct File Extension Appended onto it
- Inspecting it, it looks like it has all the Data. Scrolling to the bottom we can Verify it has the same Number of Rows in there as our DataFrame
    - This Proves, that the Export worked and included everything in there that we wanted
- Now, if we ever wanted to Read that File
    - All we'd need to do is Run `pd.read_csv('quarter_1.csv')`
    - Just need to Invoke the `.read_csv` Method and Specify the File Name along with Extension, we would want to Read

In [16]:
# Reading the CSV
pd.read_csv('quarter_1.csv')

        Unnamed: 0  ... job_posted_month
0                0  ...              Jan
1                1  ...              Jan
2                2  ...              Jan
3                3  ...              Jan
4                4  ...              Jan
...            ...  ...              ...
220479      220479  ...              Mar
220480      220480  ...              Mar
220481      220481  ...              Mar
220482      220482  ...              Mar
220483      220483  ...              Mar

[220484 rows x 19 columns]

- Inspecting it, looks like we have all of our different Data, 220K Rows
- One thing to Note with this is, the First Column we see after Reading the File
- It is called **Unamed:0**
    - We didn't specify, whenever we looked at this, that the first Column is the Index
    - Also, in the File, we never gave the Index a Name, so looking at the File there's nothing in there for the Name of the Index, it's a Blank Column Name
- What we can do when we Read the CSV is specify the Index Column. We can do this by
    - `index_col=0`
- Running this fixes that Issue

In [17]:
# Fixing the Index Issue
pd.read_csv('quarter_1.csv', index_col=0)

          job_title_short  ... job_posted_month
0            Data Analyst  ...              Jan
1          Data Scientist  ...              Jan
2           Data Engineer  ...              Jan
3           Data Engineer  ...              Jan
4          Data Scientist  ...              Jan
...                   ...  ...              ...
220479  Software Engineer  ...              Mar
220480       Data Analyst  ...              Mar
220481   Business Analyst  ...              Mar
220482      Data Engineer  ...              Mar
220483  Software Engineer  ...              Mar

[220484 rows x 18 columns]

- Let's now Export this Data into the same File Format that our Boss wants
    - Specifically into Excel
- We will use `.to_excel` for this
- Similar to `.to_csv`, we will need to specify a File Name that we want to Save it under and also specify the File Extension that we want to Save it under as well

In [20]:
# Moving onto the .to_excel Method
df_q1.to_excel('quarter_1.xlsx')

ModuleNotFoundError: No module named 'openpyxl'

- Unnfortunetly Running this will give us an Error **ModuleNotFoundError: No module named 'openpyxl'**
- Module not found
    - We will need the Python toExcel Module to actually do this
    - Let's Install it!
    - Pull up the Terminal
    - In here, we just need to Type `conda install openpyxl`
    - Only thing to Note here is to make sure you're Installing the Package into the Correct Environment
- After Installing this, and Running it again, we get the Data Exported to the Excel File, Saved into the Folder we are currently working it

In [21]:
# Running again after Install
df_q1.to_excel('quarter_1.xlsx')

- Inspecting the File we Created it has all the different Columns that we had previously
- Scrolling down to the bottom, we can see it contains the 221K Values
- NOTE: Excel has a 1 million Row Limit so that is something to consider, if the Data is Greater than 1 Million Rows

- The 3 other Methods that we need to be aware of when we become more Advanced at Python are:
1. `.to_sql`
- For this one, we would need to Import a Library, like `sqlalchemy` and then from there, we can Export it to a Database of our choosing
- If we have a Connection to it, we could Set that up as well and then Export it Directly to that
___
- These next 2 are going to Save us some time if we are dealing with really large Data Sets and we are trying to Export them and also Load them into Python very quickly
- These 2 File Types are very efficient Files. So whenever these are used, you can then Read in the Data alot quicker
- Sometimes, even faster than CSV's
2. `.to_pickle`
3. `.to_parquet`