# Pandas - Applying Functions
___
- EG: `df.apply(lambda x: x * 2)`
- We haven't even jumped into Exploring and Analyzing this `job_skills` Column that has that List of Skills and that's because there's a slight problem with this
- It's not contained as a List inside of our DataFrame right now. It's being Annotated as a String...
- Luckily, we have an **Apply** Method, for DataFrames that we are now going to be going over
    - Here we can go through and Apply something to that Column to clean it up!
- But before that, we will start with some simple examples first!

In [49]:
# Imports
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Load Dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

- For the first and second Example, we are going to be looking at the `salary_year_avg` Column
- And there's a bunch of NaN Values in there so we are going to go ahead and Filter those out first using `.notna()` Pandas Method
    - We go ahead and specify the `df`
    - In here, we Run the **Pandas** Method of notna `pd.notna()`
    - We specify where we want to Filter the NA's from, so the `df` and the Column Name, `df['salary_year_avg']`
    - Then adding in the Column Name `['salary_year_avg']` at the end so we only Return that Column, otherwise, we Return the entire df with the Filtered Results

In [26]:
# Filtering out NaN Values from salary_year_avg
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

- Now we have this back, this is the Salaries that we have
- What we want to do with this Problem is
    - We want to Calculate the Projected Salary Next Year
    - What we can do is just some rough Maths as an Example. We will Apply what Inflation is right now of around 3%
    - So basically, take the Salary Values and Multiply it times 1.03. Since the Inflation is 3% (0.3) and it will go up by that, so we need the 1 to Account for the now Values
    - Otherwise, if we only do 0.3, we will need to Add that Result to the now Values to get the Total, so might as well just lump it in there from the beginning
    - This will get to see what will be 3% higher next year
- With that, how can we actually get, inside the DataFrame how can we get it to **Apply** to this entire Column of `salary_year_avg`
    - Well! There's a Function for that!
    - `pandas.DataFrame.Apply()`
    - This can be Applied on a DataFrame, it's a Method of a DataFrame
    - Takes 1 or Multiple Arguments and we are only going to focus on the first one for the time being
        - func: It's a Function. A Function to Apply to each Column or Row
        - We will get into how we can Apply this to Rows, but for now, we will focus on 1 Column

In [27]:
# Running the Help Function on the Apply Method
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', engine: "Callable | None | Literal['python', 'numba']" = None, engine_kwargs: 'dict[str, bool] | None' = None, **kwargs) method of pandas.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument. The return type of the applied
    function is inferred based on the first computed result obtained after
    applying the function to a Series object.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

     .. note::

            When ``raw=True``, the result dtype is inferred from the **first**
            returned value.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : decorator or {'python', 'numba'}, optional
        Choose the execution engine to use. If not provided the function
        will be executed by the regular Python interpreter.

        Other options include JIT compilers such Numba and Bodo, which in some
        cases can speed up the execution. To use an executor you can provide
        the decorators ``numba.jit``, ``numba.njit`` or ``bodo.jit``. You can
        also provide the decorator with parameters, like ``numba.jit(nogit=True)``.

        Not all functions can be executed with all execution engines. In general,
        JIT compilers will require type stability in the function (no variable
        should change data type during the execution). And not all pandas and
        NumPy APIs are supported. Check the engine documentation [1]_ and [2]_
        for limitations.

        .. warning::

            String parameters will stop being supported in a future pandas version.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.

    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    References
    ----------
    .. [1] `Numba documentation
            <https://numba.readthedocs.io/en/stable/index.html>`_
    .. [2] `Bodo documentation
            <https://docs.bodo.ai/latest/>`/

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=["A", "B"])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="expand")
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=["foo", "bar"]), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="broadcast")
       A  B
    0  1  2
    1  1  2
    2  1  2

    Advanced users can speed up their code by using a Just-in-time (JIT) compiler
    with ``apply``. The main JIT compilers available for pandas are Numba and Bodo.
    In general, JIT compilation is only possible when the function passed to
    ``apply`` has type stability (variables in the function do not change their
    type during the execution).

    >>> import bodo  # doctest: +SKIP
    >>> df.apply(lambda x: x.A + x.B, axis=1, engine=bodo.jit)  # doctest: +SKIP

    Note that JIT compilation is only recommended for functions that take a
    significant amount of time to run. Fast functions are unlikely to run faster
    with JIT compilation.

- First thing we need to do, is Create a Function!
    - Start off with the `def` keyword and give it a Name of `projected_salary()`
    - It's only going to take 1 Argument of `(salary)`
    - With that Salary, what we want to `return` out of this Function is the `salary * 1.03` (so that 3% Inflation)
- From there, it's pretty simple!
- We can now take a Column of interest from our DataFrame such as `df['salary_year_avg']`
    - And use the `.apply()` on it
    - Providing the Function we Created of `projected_salary`
    - Because we are providing the Function, we don't need to provide the Parenthesis `()` after the Function. We are just Providing the Function Name, it will Apply it as necessary
- Running this on the Altered DataFrame where we Removed the NaN Values

In [28]:
# Creating a New DataFrame called df_salary and setting it equal to the Filtered DataFrame with the Removed NaN Values
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

# Creating a New Function so we can Run the apply() Method on it and get back the Results
def projected_salary(salary):
    return salary * 1.03

# Taking our Column of intrest, salary_year_avg, from our new Altered DataFrame that Removes NaN Values and Running .apply, providing the Created Function
df_salary['salary_year_avg'].apply(projected_salary)

28        112785.00
77        144200.00
92        123600.00
100       235068.66
109        91670.00
            ...
785624    143392.48
785641    154500.00
785648    228531.25
785682    162225.00
785692    162225.00
Name: salary_year_avg, Length: 22003, dtype: float64

- Now we have back all those different Salary Values!
- Now, let's actually inspect this and see how it Compares to that Original `salary_year_avg` Column
- So, we will Create a New Column inside our Filtered DataFrame called `salary_year_inflated` and Set it Equal to what we did above with Multiplying `salary_year_avg` by the Created Function
- And then for the New Filtered DataFrame, I want to show, these 2 Columns of `salary_year_avg` and `salary_year_inflated`
    - Doing this, we can Compare the Values in the 2 Columns against each other
    - Easier to see when we Compare the Original Value to the Inflated Value
    - Now we can see the Projected Value as it Compares to the Original Value

In [29]:
# Creating a New Column in the DataFrame to Compare the Values against
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

# Printing out the 2 Columns from the New DataFrame to Inspect them and Compare Values
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

- Inspecting this further, we can see that `salary_year_avg` Column was Multiplied times 1.03
- Looking at the Function, we can see that it's pretty short... and Providing the `.apply()` Method this Created Function, we could use something like an **Anonymous Function**
    - So let's try writing this again with an **Anonymous Function**
        - Declaring our New Column Name of `salary_year_inflated` and Creating it in our `df_salary`with this notation: `df_salary[salary_year_inflated] = `
        - Define `df_salary` again so we can assign what we are going to do to the Old Column, in this case, manipulate the `salary_year_avg` Value and store it in our New Column
        - The notation will be `df_salary['salary_year_avg']`
        - Then we will Apply a Lambda Funtion to it using `.apply()`
            - For this because we haven't used Lambda Functions for a while... so we will need a Reminder!
            - Define `lambda`
            - Then Define a specific Variable, so in this case, we will define `salary`
            - Then you will need to Add a Colon `:` so it will look like this `salary:`
            - After the Colon, you will need to provide whatever Mathematical Equation/Operation you want it to do! In our case, we want `salary * 1.03`
    - Then once again we will want to see, what the `salary_year_inflated` Column looks like, compared to the `salary_year_avg` Column so we will want to Print both of those out
    - Notation is `df_salary[['salary_year_avg', 'salary_year_inflated']]`

In [30]:
# Doing the exact same Function but this time doing it via an Anonymous Function
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

# Printing out the 2 COlumns for Comparison
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

- Once again, comparing it to the last one, we get the same Results, which means all the Math was done correctly with the Anonymous Function
- For the hard-core Data Nerds, you may have noticed, that we can re-write this without the `.apply()` Method or Lamda Function!
    - Since, all we are actually doing is, Multiplying 1.03 by another Number in the `salary_year_avg` Column
    - And the Printing out the 2 different Columns to see what the difference is
    - Since this is an overly simplistic example, we don't have to use any of these Methods or Functions, we can just do the Maths on this explicitly
    - See below what I mean!
- But this was mainly to show an Introduction to the `.apply()` Method when Running it on a Column!

In [31]:
# Doing the Math Raw and Explicitly, without Lambda or Apply Functions
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'] * 1.03

# Printing them both out
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

- So let's actually use this `.apply()` Method in a situation where it's actually Applicable and you can't actually Simplify it!
    - That's in the context of our `job_skills` Column
    - Specifically, we need to Convert this from a String into a List
- If we wanted to Display the List of Skills from the second Record of our DataFrame, we can do it as such

In [32]:
# Displaying the List of Skills from the second Record of the DataFrame
df['job_skills'][1]

"['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']"

- After Running, we can see that the List has double Quotes around it...
- And even wrapping it with a `type()` Method, we can Confirm that it is in fact, a String

In [33]:
# Running Type() to Confirm it's DataType
type(df['job_skills'][1])

str

- So how can we actually Convert this back to a List?
- You could wrap certain Objects inside of a DataType like List and then try to Convert it...
- However, in this case, if we were to try this we get....

In [34]:
# Converting the String Type List, into a List
list(df['job_skills'][1])

['[',
 "'",
 'r',
 "'",
 ',',
 ' ',
 "'",
 'p',
 'y',
 't',
 'h',
 'o',
 'n',
 "'",
 ',',
 ' ',
 "'",
 's',
 'q',
 'l',
 "'",
 ',',
 ' ',
 "'",
 'n',
 'o',
 's',
 'q',
 'l',
 "'",
 ',',
 ' ',
 "'",
 'p',
 'o',
 'w',
 'e',
 'r',
 ' ',
 'b',
 'i',
 "'",
 ',',
 ' ',
 "'",
 't',
 'a',
 'b',
 'l',
 'e',
 'a',
 'u',
 "'",
 ']']

- This absolute jumble of letters back...
- It turns it into a jumbled mess that is not possible to read...
- It Converts every single Letter into it's own Item, into a List
- Basically it doesn't work!

- Instead, we are going to use the `ast` Module! Which stands for **Abstract Syntax Trees**
- This is special for our Unique use case and not something that would be common
    - `ast.literal_eval()`
        - With this, you provide a Node or a String (In our case, we are going to Provide that String to it)
        - Basically goes through and it Converts it to the Container DataType, in our case a List - Back to what it's supposed to be!
- Let's actually show this in action!
    - First we will need to Import in the `ast` Module and it's apart of the Python Standard Library so no Install required - `Import ast`
    - Then we are going to Apply the `literal_eval()` Function on the `df` for the String List Column of `job_skill` and only for the Second Record to see it working

In [36]:
# Importing in the Module
import ast

# Running literal_eval() on the String List Column to Convert it to a List only! Doing it for 1 Record first to see it working
ast.literal_eval(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

- Now we have this back into a List
- We can also Confirm this by Running `type()` on this as well and seeing it

In [37]:
# Running type on this
type(ast.literal_eval(df['job_skills'][1]))

list

- It comes back as a List and Confirms that the Conversion was Successful!
- So let's now clean up this Column using the `Apply` Function
- Just as a Note as well! We can't actually Run `ast.literal_eval()` on this entire Column. We are unable to explicitly do this
- If we try and do this, we will get a Value Error as we didn't pass in the stuff correctly, we **have** to use the `apply()` Method for this

In [38]:
# Trying literal_eval() explicitly on the Column
df['job_skills'] = ast.literal_eval(df['job_skills'])

ValueError: malformed node or string: 0                                                       NaN
1         ['r', 'python', 'sql', 'nosql', 'power bi', 't...
2         ['python', 'sql', 'c#', 'azure', 'airflow', 'd...
3         ['python', 'c++', 'java', 'matlab', 'aws', 'te...
4         ['bash', 'python', 'oracle', 'aws', 'ansible',...
                                ...
785736    ['bash', 'python', 'perl', 'linux', 'unix', 'k...
785737                       ['sas', 'sas', 'sql', 'excel']
785738                              ['powerpoint', 'excel']
785739    ['python', 'go', 'nosql', 'sql', 'mongo', 'she...
785740                                      ['aws', 'flow']
Name: job_skills, Length: 785741, dtype: str

- First thing we are going to do is to Create a Function
- Using the `def` keyword, and naming it `clean_list()`
- We will need to Pass in a Variable as well, so we will call it `skill_list`
    - Notation so far is `def clean_list(skill_list):`
- This Function is going to be going through each of those Items in the Column so we can Return that Literal Eval of our Skill List like so
    - Notation is `return ast.literal_eval(skill_list)` 
- Now that the Function is done, let's write out our `apply()` Function
    - For this, we just want to Replace it, right on top of the Original Column of `job_skills` so we will set it equal to itself
    - Then using the `.apply()` Method we will pass in our Created Function
    - Notation will be `.apply(clean_list)`
- Running this, will actually give us an Error!
    - Specifically, we get a **ValueError**
    - This is because of a Malformed Node or String... it's basically because we have NaN Values in our String List

In [39]:
# Writing our Function to Convert the String List into a List and Return only the List
def clean_list(skill_list):
    return ast.literal_eval(skill_list)

# Using the Apply Function to grab our Created clean_list Function in order to Clean the List
df['job_skills'] = df['job_skills'].apply(clean_list)

ValueError: malformed node or string: nan

- We can show this by Filtering the DataFrame to only show NA Values inside of the `job_skills` Column
- We can do this by using `.isna()` Function and passing in what Column we want to Filter it for

In [42]:
# Using isna Function to see the Jobs that don't have Skills Listed
df[pd.isna(df['job_skills'])]

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
21,Data Scientist,Stage - data scientist – génération ia de donn...,"Asnières-sur-Seine, France",via Jobijoba,Full-time,False,France,2023-02-23 13:41:21,False,False,France,NaN,NaN,NaN,Credit Agricole,NaN,NaN
26,Data Engineer,Data Engineer,United States,via LinkedIn,Full-time,False,Georgia,2023-09-15 13:56:18,True,False,United States,NaN,NaN,NaN,Infinite Computer Solutions,NaN,NaN
29,Data Scientist,Data Scientist,"Pune, Maharashtra, India",via Exusia,Full-time,False,India,2023-03-26 13:16:20,False,False,India,NaN,NaN,NaN,Exusia,NaN,NaN
36,Data Analyst,Data Analyst,"Des Moines, IA",via Trabajo.org,Full-time,False,"Illinois, United States",2023-11-06 13:01:22,False,True,United States,NaN,NaN,NaN,Assuredpartners,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785713,Cloud Engineer,"Data Center Chief Engineer, AWS Infrastructure...","Bangkok, Thailand",melalui LinkedIn,Pekerjaan tetap,False,Thailand,2023-03-12 06:37:47,False,False,Thailand,NaN,NaN,NaN,Amazon Web Services (AWS),NaN,NaN
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,NaN,NaN,NaN,Amul,NaN,NaN
785718,Business Analyst,Senior Performance QA Analyst,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,NaN,NaN,NaN,Diebold Nixdorf,NaN,NaN
785724,Data Engineer,Junior Consultant Data Engineering,"Koln, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,False,False,Germany,NaN,NaN,NaN,Target Reply,NaN,NaN
785729,Data Engineer,Data Engineer Marketing Intelligence,Jerman,melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,IU Internationale Hochschule,NaN,NaN

- Inspecting the Results and looking at our `job_skills` Column, we can see that we have a bunch of NaN Values
- This is causing Errors for us here, because it's trying to do the `literal_eval` on NaN when it's expecting a String to be Passed
- How do we fix it?
    - We can Pass in an `if` Statement inside of our Created Function which checks if the Value is `notna()` then do the `literal_eval` and Return the Manipulated Value
    - If it is NaN, we do nothing and skip it leaving it as is
    - Using the `pd.notna()` Function and passing in our `skill_list`
    - If it's not NA (has a Value) then we Return it as a List otherwise, we are going to leave it None

In [44]:
# Writing the Function with an if Statement inside of it to check for non NaN Values
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
    
# Using the Apply Function to grab our Created clean_list Function in order to Clean the List
df['job_skills'] = df['job_skills'].apply(clean_list)

- Everything Ran right and there were no errors, which indicates Success!
- But let's actually Inspect the second element of this to Confirm if the `job_skills` are now in a List

In [45]:
# Inspecting the second record to make sure it's in a List
df['job_skills'][1]

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

- Printing it out, it is now in a List as we got a List back!
- Confirming the Type of this by Running the `type()` Function on this

In [53]:
# Confirming Typing
type(df['job_skills'][1])

list

- We can see that it is infact a List!
- This Confirms, that it did do the Conversion correctly!
- In this case, because of how simple this Function is... it's encouraged, that we make this into a `lambda` Function
    - It's important to Note, it's good to write a Function first, and then Convert it afterwards!
- Starting this off the same way, by overwriting the Original `job_skills` Column with what we do to it. To do this, like always, we make it equals itself 
    - `df['job_skills'] = df['job_skills']`
- We then Invoke the apply as well which again is the same 
    - `.apply()`
- Inside the `apply()` brackets is where we do our `lambda` action
    - Start be defining `lambda` and define the Variable that we want to use, we will call it `clean_skills`
    - Then it will be followed by a Colon as well! So it will look like `lambda clean_skills:`
    - Now we get into what we actually want to do, we want to perform the converstion on the Variable and change it from a String List to just a List
    - We do an `ast.literal_eval()` to accomplish this and we pass in the `lambda` Variable we defined like this - `ast.literal_eval(clean_skills)`
    - Running just that, we will get the same Error as before, complaining about NaN Values, so we will need to Filter those out using an `if` Statement
    - The `if` Statement needs to be included inside of our `lambda`. It will be same as the one we Created above. We need to put it **after** the `literal_eval` Statement
        - Since it's the same it will be `if pd.notna(clean_skills)`
    - Running just this, we will also get an Error!
        - This is because it won't know what to do with the NaN Values and it expected an `else` after the `if`
    - Adding in the `else` to just Return back that `clean_skills` List if it is None/NaN Value (what the Value is currently)

In [50]:
# Doing the exact same Function but this time doing it via an Anonymous/lambda Function
df['job_skills'] = df['job_skills'].apply(lambda clean_skills: ast.literal_eval(clean_skills) if pd.notna(clean_skills) else clean_skills)

- Running this, everything looks like it Ran fine
    - But we can check and Confirm with the `type` Function to make sure the Records are of Type List

In [55]:
# Confirming it's a List with the type Function
type(df['job_skills'][1])

list

- It is in fact a List!
- Going forward, when we actually analyze the Skills, we will be using the above Anonymous Function to clean the String List into a List using the `literal_eval` Method along with the `if` Statement
- It will be included, inside of the usual Imports, Loading Data and Data Cleaning that we do before starting a Lesson
- This is a very important bit of Code, so we need to understand what it's doing going forwards because we will be using it from now on

- Now, before finishing up, there is 1 more Example to civer using the `apply()` Method
- Because so far, we have only been focussing on Applying it to a Column...
    - But in the future, we may need to Apply it to a "condition of" a Row!
    - So previously we went through and applied 3% Inflation to every single Salary
    - Let's say we have a New Problem, where we're assuming that for Senior Roles they are going to have an Inflation/Projected Salary of 5% higher
    - Where, the other Roles are only 3%
    - So we are going to need to Revise the Code, that we did previously in order to do this more complex `apply()` Method
        - Code I'm refering to is below... (since it was a bit ago)

In [56]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [58]:
# Running the help() Function on the apply() Method
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', engine: "Callable | None | Literal['python', 'numba']" = None, engine_kwargs: 'dict[str, bool] | None' = None, **kwargs) method of pandas.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument. The return type of the applied
    function is inferred based on the first computed result obtained after
    applying the function to a Series object.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

     .. note::

            When ``raw=True``, the result dtype is inferred from the **first**
            returned value.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : decorator or {'python', 'numba'}, optional
        Choose the execution engine to use. If not provided the function
        will be executed by the regular Python interpreter.

        Other options include JIT compilers such Numba and Bodo, which in some
        cases can speed up the execution. To use an executor you can provide
        the decorators ``numba.jit``, ``numba.njit`` or ``bodo.jit``. You can
        also provide the decorator with parameters, like ``numba.jit(nogit=True)``.

        Not all functions can be executed with all execution engines. In general,
        JIT compilers will require type stability in the function (no variable
        should change data type during the execution). And not all pandas and
        NumPy APIs are supported. Check the engine documentation [1]_ and [2]_
        for limitations.

        .. warning::

            String parameters will stop being supported in a future pandas version.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.

    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    References
    ----------
    .. [1] `Numba documentation
            <https://numba.readthedocs.io/en/stable/index.html>`_
    .. [2] `Bodo documentation
            <https://docs.bodo.ai/latest/>`/

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=["A", "B"])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="expand")
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=["foo", "bar"]), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type="broadcast")
       A  B
    0  1  2
    1  1  2
    2  1  2

    Advanced users can speed up their code by using a Just-in-time (JIT) compiler
    with ``apply``. The main JIT compilers available for pandas are Numba and Bodo.
    In general, JIT compilation is only possible when the function passed to
    ``apply`` has type stability (variables in the function do not change their
    type during the execution).

    >>> import bodo  # doctest: +SKIP
    >>> df.apply(lambda x: x.A + x.B, axis=1, engine=bodo.jit)  # doctest: +SKIP

    Note that JIT compilation is only recommended for functions that take a
    significant amount of time to run. Fast functions are unlikely to run faster
    with JIT compilation.

- Previously, we only covered the Function aspect of it, but now we need to look at the `axis`
    - Default currently is 0, which means that it applied the Function to each Column...
    - But if we want to Apply a Function to a Row, so we can access multiple Columns in a Row or check a Column this is what we want to use
- Because this one is a little bit more Complex, we are going to be building a Function first, and then Passing it into our `apply()` Method
- Let's start by Building out, how we are going to use that `apply()` Method
    - For this, we are going to be using the `df_salary` DataFrame again because it already has all of the Salary Data Filtered out and makes it easier to Display
    - First we are going to be Creating a New Column of `salary_year_inflated` and in this case, instead of providing the DataFrame and the Column we are just going to provide the DataFrame
        - Because we want the entire Row to go to it this time
        - We are going to Run the `apply()` Method on that
        - We are going to be using a Function (that is pending Creation at this point) but it will be called `projected_salary`
        - This will be passed into the `apply()`
        - Specify the Parameter of `axis=1`
- Now it's time to start building out the Function
    - Starting off as usual with the `def` Keyword, the name of `projected_salary()`
    - Inside of it, we will be Passing the Row so we call the Variable, `row`
        - What we need to do inside of this as it's grabbing each one of these Rows is check what the Value is in the `job_title_short` Column
            - If it's **not** Senior, take the `salary_year_avg` and Multiply it by 1.03 
            - If it **is** Senior, take the `salary_year_avg` and Multiply it by 1.05
            - This is a great `if` Statement
            - It will look like this, `if "Senior" in row['job_title_short']:` `return 1.05 * row['salary_year_avg']`
            - Then we will need an `else` Statement to handle all the other Values
            - It will look like this, `else: return 1.03 * row['salary_year_avg']`
- For Printing, we want to Display, the `job_title_short`, `salary_year_avg` and the `salary_year_inflated`
    - To do this, we do the usual `df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]`

In [63]:
# Building the row Example
# Function that Calculates: Senior Roles are going to have an Inflation/Projected Salary of 5% higher and the other Roles are only 3%
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']

# Apply Function, we want to apply the entire DataFrame, so as to give the Function access to every Column in the whole DataFrame and axis=1 so it Applies to the Rows instead of Columns 
df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

# Printing out to see the Results
df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']].head(17)

          job_title_short  salary_year_avg  salary_year_inflated
28         Data Scientist         109500.0             112785.00
77          Data Engineer         140000.0             144200.00
92          Data Engineer         120000.0             123600.00
100        Data Scientist         228222.0             235068.66
109          Data Analyst          89000.0              91670.00
116        Data Scientist         114000.0             117420.00
146         Data Engineer         129500.0             133385.00
180          Data Analyst          90250.0              92957.50
212        Data Scientist         157500.0             162225.00
257        Data Scientist         103128.0             106221.84
307         Data Engineer         185000.0             190550.00
339         Data Engineer         195000.0             200850.00
380         Data Engineer          97500.0             100425.00
388         Data Engineer          89000.0              91670.00
410          Data Analyst         133285.0             137283.55
450        Data Scientist         157500.0             162225.00
495  Senior Data Engineer         168500.0             176925.00

- Running this, all the Values are going to Fill in depending on if it's a Senior Role or not, and we can see that it worked correctly
- If it's a Senior Role, it's doing the 1.05 Multiplication Formula and for everything that's **not** a Senior Role, we can see it did the 1.03 Multiplication Formula
- The above Code, can actually be Transformed and written into a `lambda` Function as well
    - This will simplify it into one line... buuuut it does start to look really long but it can be done
- See below, the same Function as above, doing the exact same Calculation but in the form of a `lambda` Function

In [64]:
# Doing the same Function as above, but as a Lambda Function
df_salary['salary_year_inflated'] = df_salary.apply(lambda row: 1.05 * row['salary_year_avg'] if "Senior" in row['job_title_short'] else 1.03 * row['salary_year_avg'], axis=1)

# Printing it out
df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']].head(17)

          job_title_short  salary_year_avg  salary_year_inflated
28         Data Scientist         109500.0             112785.00
77          Data Engineer         140000.0             144200.00
92          Data Engineer         120000.0             123600.00
100        Data Scientist         228222.0             235068.66
109          Data Analyst          89000.0              91670.00
116        Data Scientist         114000.0             117420.00
146         Data Engineer         129500.0             133385.00
180          Data Analyst          90250.0              92957.50
212        Data Scientist         157500.0             162225.00
257        Data Scientist         103128.0             106221.84
307         Data Engineer         185000.0             190550.00
339         Data Engineer         195000.0             200850.00
380         Data Engineer          97500.0             100425.00
388         Data Engineer          89000.0              91670.00
410          Data Analyst         133285.0             137283.55
450        Data Scientist         157500.0             162225.00
495  Senior Data Engineer         168500.0             176925.00